version: 1

project_name: CHALLENGE-NAME

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go generate ./...

env:
  - CGO_ENABLED=0

builds:
  - goos: [linux, windows, darwin]
    ldflags: [-s -w]

upx:
  - enabled: true
    goos: [linux]
    compress: best
    lzma: true
    brute: true
  - enabled: true
    goos: [windows]
    goarch: ["386", amd64]
    compress: best
    lzma: true
    brute: true
  - enabled: true
    goos: [darwin]
    goarch: ["386", arm]
    compress: best
    lzma: true
    brute: true
